	-- 테이블 생성
    CREATE TABLE SPRING_REPLY(
        R_NUM NUMBER NOT NULL ,
        B_NUM NUMBER NOT NULL ,
        R_NAME VARCHAR2(10) NULL ,
        R_CONTENT VARCHAR2(2000) NULL ,
        R_PWD VARCHAR2(18) NULL ,
        R_DATE DATE DEFAULT SYSDATE,
        CONSTRAINT SPRING_REPLY_PK PRIMARY KEY(R_NUM),
		CONSTRAINT SPRING_REPLY_FK FOREIGN KEY(B_NUM) REFERENCES SPRING_BOARD(B_NUM)
    ) ;
    
    
    COMMENT ON TABLE  SPRING_REPLY IS '댓글 정보';
    COMMENT ON COLUMN SPRING_REPLY.R_NUM IS '댓글번호';
    COMMENT ON COLUMN SPRING_REPLY.B_NUM IS '게시판 글번호';
    COMMENT ON COLUMN SPRING_REPLY.R_NAME IS '댓글 작성자';
    COMMENT ON COLUMN SPRING_REPLY.R_CONTENT IS '댓글 내용';
    COMMENT ON COLUMN SPRING_REPLY.R_PWD IS '댓글 비밀번호';
    COMMENT ON COLUMN SPRING_REPLY.R_DATE IS '댓글 등록일';   
    
    CREATE SEQUENCE SPRING_REPLY_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;
